# Generated by Django 5.0.3 on 2024-07-07 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomStatus",
            fields=[
                (
                    "room",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "room_status",
                "verbose_name_plural": "room_status",
                "db_table": "room_status",
                "ordering": ["-created_at"],
            },
        ),
    ]
