# Generated by Django 5.0.3 on 2024-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_status_id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='password',
        ),
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
