# Generated by Django 5.0.3 on 2024-09-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_rooms_room_status_id_remove_rooms_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
