# Generated by Django 5.0.3 on 2024-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_messages_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="room_type",
            field=models.CharField(
                choices=[("dm", "Direct Message"), ("group", "Group")],
                default="group",
                max_length=5,
            ),
        ),
    ]
