FROM prom/alertmanager:latest

# スクリプトをコンテナにコピー
ADD ./entrypoint.sh /usr/local/bin/entrypoint.sh

# 実行権限を付与
USER root
RUN chmod +x /usr/local/bin/entrypoint.sh

# エントリポイントを指定
ENTRYPOINT ["entrypoint.sh"]

CMD ["/bin/alertmanager", "--config.file=/alertmanager/alertmanager.yml", "--storage.path=/alertmanager/data"]
