global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - '/etc/prometheus/server-down.rules'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['app:8000']
    basic_auth:
      username: 'admin'
      password: 'password123'
      
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
