global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/metrics/metrics"
    scheme: 'http'
    static_configs:
      - targets: ['app:8000']
    basic_auth:
      username: "admin"
      password: "password123"
