# Generated by Django 5.0.3 on 2024-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='/static/pong/img/test.jpeg', null=True, upload_to='user_icons/'),
        ),
    ]
