# Generated by Django 5.0.3 on 2024-07-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='defaults/default.jpeg', null=True, upload_to='uploads'),
        ),
    ]
