# Generated by Django 5.0.3 on 2024-10-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0002_user_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="sample", max_length=20, unique=True),
        ),
    ]
