# Generated by Django 5.0.3 on 2024-10-06 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0003_friend_friendrequest_friend_user_friend_unique_and_more"),
        ("pong", "0003_user_nickname"),
    ]

    operations = []
