# Generated by Django 5.0.3 on 2024-08-23 07:07

import pong.utils.random_string
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0003_uses2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="users2fa",
            name="secret",
            field=models.CharField(
                default=pong.utils.random_string.generate_base32_encoded_random_string
            ),
        ),
    ]
