# Generated by Django 5.0.3 on 2024-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0004_merge_20241006_0920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="sample", max_length=20),
        ),
    ]
