# Generated by Django 5.0.3 on 2024-10-12 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0006_alter_user_nickname"),
        ("pong", "0006_users2fa"),
    ]

    operations = []
