# Generated by Django 5.0.3 on 2024-08-27 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realtime_pong_game", "0005_matchinfo_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchinfo",
            name="winner",
        ),
    ]
