FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app


COPY requirements.txt ./requirements.txt

RUN python -m venv /app/.venv && \
	. /app/.venv/bin/activate && \
	pip install -r requirements.txt

RUN echo 'source /app/.venv/bin/activate' >> ~/.bashrc

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]




