FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=20.16.0

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN python -m venv /app/.venv && \
	. /app/.venv/bin/activate && \
	pip install -r requirements.txt

COPY .nvmrc package.json package-lock.json eslint.config.mjs /app/

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    npm install


RUN echo 'source /app/.venv/bin/activate' >> ~/.bashrc

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]




